sudo: required
language: java
jdk:
  - openjdk10
services:
- docker
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - docker
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bren@juanantonio.info
script:
  - ./mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
